version: '3'
services:
  docker-app:
    image: star-wars-image
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=loja-lets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=150197